### ISSUE TITLE
Fix Search/Filter wrapper - visual

### ISSUE THREAD

**Issue by ChrisCooper0** [MK-Codecademy/Rest-Countries-API#41]
The mobile the search bar should be around 90% width and central. Currently it is a little shorter so there is more spacing on the right than the left.

The Search bar padding could also better match the design guide.

**Comment by willgarrett64** [comment]
Hey, @ChrisCooper0  - it's looking much better, but I just reopened it because of one sliiiight issue. In the image/video you can see in mobile mode the wrapper is 90% and central, but the search bar doesn't quite reach the end of the wrapper. 

I think once it's stacked like this for mobile, the search bar needs a width of 100%? 

https://www.loom.com/share/58931cb1f1c64d8799508b0b5e13bdca
![image](https://user-images.githubusercontent.com/74154911/127920200-5a3112b2-19de-46be-82ba-b13373b6bb1d.png)

**Comment by ChrisCooper0** [comment]
Ah let me take another look. I'm working with vw rather than % but should be a quick fix!
